### ISSUE TITLE
Unable to find features and step definitions

### ISSUE THREAD

**Issue by svalchinov** [commercehub-oss/gradle-cucumber-jvm-plugin#10]
I am trying to get the example configuration from the README file working but it seems I have the wrong source and module structure.

I have the following:

src -> cucumberTest -> java (glue dir)
src -> cucumberTest -> resources (feature dir)
src -> main -> java (empty)
src -> test -> java (empty)    

When I run `gradle cucumberTest` I get empty results where no features or step definitions are recognised.

Any ideas?

**Comment by JayStGelais** [comment]
If you're using the example configuration from the README, your features will need to specifically be under:

src-> cucumberTest->resources->features

and you glue under one of the following folders:

src-> cucumberTest->java->cucumber->steps
src-> cucumberTest->java->cucumber->hooks

By default re root features and glue in specific packages to avoid scanning the entire classpath.

**Comment by svalchinov** [comment]
Thanks, that worked perfectly! I apologise for the silly question. It should have been clear from the task configuration docs.

> stepDefinitionRoots: A list of root packages to scan the classpath for glue code. Default to ['cucumber.steps', 'cucumber.hooks']

> featureRoots: A list of root packages to scan the resources folders on the classpath for feature files. Defaults to ['features']

**Comment by JayStGelais** [comment]
No problem. Glad you have it working. 

I'll close the issue.
