### ISSUE TITLE
Making the pluing available from gradle plugin repository

### ISSUE THREAD

**Issue by mat013** [commercehub-oss/gradle-cucumber-jvm-plugin#13]
Are there any plans to release this plugin to the gradle repository?

At the moment it seems not to be available from the gradle plugin repository, so we have to build it ourself, and due to the security policy I have to adjust the build files to cater for these restriction, so it would be nice if this was available from the gradle plugin repository, which seems to be whitelisted

**Comment by JayStGelais** [comment]
I can take a look at this in the next few days. I've personally never published a plugin to the repository, so I will have to look into what that process is.

**Comment by JayStGelais** [comment]
I've attempted to publish an initial version. It's pending approval by the gradle team.

The build has been updated to include publishing to the plugin portal as part of every future release.
