### ISSUE TITLE
Suggestion: Making the plugin scan for .feature files in java and resource folder instead of only the resource folder

### ISSUE THREAD

**Issue by mat013** [commercehub-oss/gradle-cucumber-jvm-plugin#14]
Currently the .feature files are put in the resource files and the step definition files are added to the java folder. 

It seems a little disseparate when they are connected other and I was thinking if it would be better to have them together. I was thinkg about making it possible to have feature files in the java folder.

And then scanning the allSource folder instead of the resource folder when looking for feature files:

The change I had in mind is the following in CucumberRunner

Instead of following line:

```
    def features = sourceSet.resources.matching {
```

Then it should be

```
    def features = sourceSet.allSource.matching {
```

I will be happy to make the change if it will be accepted

But let me know

**Comment by JayStGelais** [comment]
By convention, the java folder in a source set should only contain java source files. Other resources the program depends on (such as feature files) should be in the resources folder. 

That being said, the plugin should probably be scanning the output dir for the source set in case the need were to ever arise for their to be a processing step, such as token substitution, on the feature files. That change would effectively give you the (unrecommended) option to commingle feature files with the java source files as they all end up in the same output directories.

**Comment by mat013** [comment]
You are right that strictly speaking .feature should be in resources and it is merely a convenience when using and IDE that .feature files and step files are in the same folder structure

However if #15 is accepted I can work around it by using inheritance, and this one can be closed then

**Comment by JayStGelais** [comment]
Closing this issue as the referenced Pull request was merged.
