### ISSUE TITLE
Cucumber test with undefined steps are passing

### ISSUE THREAD

**Issue by mat013** [commercehub-oss/gradle-cucumber-jvm-plugin#15]
I have run a cucmber test and I can see that it ran, however some of the step was missing and the build passed. I expected it to fail, and I looked in the feature-out.log(attached some of the log) and I can see that the cucumber test is failing. My expectation was the build should fail as well? or is this intended behaviour?

1 Scenarios ([33m1 undefined[0m)
1 Steps ([33m1 undefined[0m)
0m0.029s

You can implement missing steps with the snippets below:

@Then("^aaathe base(\d+) encoded contalsdkjdaladjaljalsdladsent in trade (\d+) contains$")
public void aaatheBaseEncodedContalsdkjdaladjaljalsdladsentInTradeContains(int arg1, int arg2, String arg3) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

**Comment by mat013** [comment]
I investigated the issue and the issue is that the plugin is using an old version of masterthought... 0.6.0 and current is 2.5.0.

Maybe it is time to change to a newer version, at the same time it would be nice to also upgrade some of the other tools such as gradle to 2.14 instead of 2.5

I do not know if I will have the time to do so, but what do you guys think?

**Comment by JayStGelais** [comment]
Whether or not to fail on undefined steps can be controlled with the `isStrict` option. The default is false, but if turned on it will fail for undefined or pending steps.

**Comment by JayStGelais** [comment]
As far as the upgrades, I can probably give that a try in the next few days. If the upgrades are seamless, I'll include them in the next release.

**Comment by mat013** [comment]
Ok that is fine as well I have already implemeted the upgrade, so if you
want it I can try to integrate it into as soon as I have the time... (Hint
it is not that seamless :) )

**Comment by JayStGelais** [comment]
If you have a pull request you can submit with the upgrades it will be reviewed and potentially (very likely) accepted

**Comment by JayStGelais** [comment]
Masterthoughts has been upgraded as discussed in this thread. Closing issue.
