### ISSUE TITLE
Suggestion: When feature file is empty cucumber fails silently

### ISSUE THREAD

**Issue by mat013** [commercehub-oss/gradle-cucumber-jvm-plugin#18]
While trying to write some .feature file I forgot to write something in a .feature file.

To my big surprise the build succeeds eventhough there is something in stderr.

I would like to suggest that the build fails in case that there is something in stderr.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
