### ISSUE TITLE
#ThisIsNOTAnIssue# Question -  on how to run tests without creating Test suite?

### ISSUE THREAD

**Issue by anoopwebs** [commercehub-oss/gradle-cucumber-jvm-plugin#20]
Hey Jay, I was going through this github repo and trying to implement in my work. As you mentioned in readMe, Cucumber tasks can be configured at two levels, globally for the project and individually for a test suite but I couldn't able to do it in globally. If you don't mind could you please help me out there?  

Our Framework is simple enough 

Src
- main
-- java
--- pageObjects
- test
--java
--- steps
-- resources
--- features

features package includes different features and each feature contains multiple scenarios. I was looking for running some of the scenarios from every feature file depends on the tag

Thanks in advance - Anoop Philip

**Comment by JayStGelais** [comment]
You'll either want to change the package your steps live in or configure the build to look in the package you are using. The default is 'cucumber.steps' (src/test/java/cucumber/steps if your steps live in the test source set). you could configure your build with the following snippet to not have to change where they are located:
`
cucumber {
    stepDefinitionRoots = ['steps']
}
`

Tags can be passed to the cucumber runner using the tags property on the cucumber (or task) configuration. This property takes a list of strings that are the tag names. An empty list causes the runner to run all tests. If you want to pass tags in on the command line, script your build to pass a the value of a build property to this plugin/task property.

**Comment by JayStGelais** [comment]
Closing as this question was addressed.
