### ISSUE TITLE
Document software dependencies/compatibility

### ISSUE THREAD

**Issue by mhurne** [commercehub-oss/gradle-cucumber-jvm-plugin#23]
Please document gradle-cucumber-jvm-plugin's software dependencies/compatibility, especially its Gradle and Cucumber dependencies/compatibility.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
