### ISSUE TITLE
Please provide contribution guidelines

### ISSUE THREAD

**Issue by davidmc24** [commercehub-oss/gradle-cucumber-jvm-plugin#24]
Please create a CONTRIBUTING.md that covers:
- How people are expected to contribute to the project
- The process for building/testing the project

**Comment by Luxor** [comment]
+1

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
