### ISSUE TITLE
[Question] about multiple tags support

### ISSUE THREAD

**Issue by acorse** [commercehub-oss/gradle-cucumber-jvm-plugin#32]
Hello,

I'm trying to setup the use of the plugin and it seems that the multiple tags are not supported.
I have 2 feature files with a tag @login located at feature level and on a specific scenario I have a ~@ignore tag.

Problem, when tests are run (gradlew clean cucumberTest), all tests are run and the scenario that should be ignored is not ignored.

Do you have input on this ? Am I wrong with my syntax (I want @login AND NOT @~ignore) ? 

`addCucumberSuite 'cucumberTest'

cucumber {
    maxParallelForks = 3
}

// See https://github.com/commercehub-oss/gradle-cucumber-jvm-plugin#cucumber-task-configuration
cucumberTest {
    stepDefinitionRoots = ['com.xxx.cucumber.steps', 'com.xxx.cucumber.hooks']
    featureRoots = ['com/xxx/cucumber/features']
    tags = ['@login', '~@ignore']
    maxParallelForks = 3
}

dependencies {
    cucumberTestCompile([group: 'info.cukes', name: 'cucumber-java', version: "$cukesVersion"])
}`

Another test, several scenarios different tags @scenario1 for s1, @scenario2 for s2, @scenario3  for s3.
If I'm right, tags = ['@scenario1,@scenario2'] should run scenario having tag  @scenario1 OR @scenario2 (which matches s1 and s2). Problem only s1 is played.

Thanks

**Comment by fernandotnl** [comment]
I created a PR to fix this: https://github.com/fernandotnl/gradle-cucumber-jvm-plugin/pull/1

**Comment by acorse** [comment]
Sounds good, thank you
