### ISSUE TITLE
How to register cucumber plugin (plugin in cucumber options)

### ISSUE THREAD

**Issue by SM-Rahman** [commercehub-oss/gradle-cucumber-jvm-plugin#34]
My runCukeTest.java has a plugin configuration in cucumber options. How to configure this custom plugin with gradle? 

Configuration in java.

@CucumberOptions (features = "src/cucumberTest/resources/features",
								//tags={"@QE"},
										plugin = {
								                "com.sample.test.commons.clogger.CLoggerPlugin:build/reports/logs/cucumber-execution.log",								                
								                "json:build/reports/QE/cucumberTest/json/mytest-report.json"
								        },
										format = {"pretty","html:build/reports/QE/cucumberTest/html","json:build/reports/QE/cucumberTest/json/report.json"}
								)

**Comment by andrcuns** [comment]
I think this should be closed as plugin support is added.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
