### ISSUE TITLE
Error when running - StatusLogger

### ISSUE THREAD

**Issue by IvanAtanasov** [commercehub-oss/gradle-cucumber-jvm-plugin#38]
Hi,

I'm trying out the plugin (version 0.11) and getting this error in the output:

> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

Other than that the cucumber tests are being executed and the build finishes successfully.

Am I supposed to create a log4j config file to specify what output I want. It is not documented anywhere and seems a bit strange that I'd have to do that. It would be nice to see some sort of out put when all tests have passed.

Also it only seems to happen on the fist build of a project using the plugin.

Thanks,
Ivan

**Comment by andrcuns** [comment]
I'm fairly certain that it comes from https://github.com/damianszczepanik/cucumber-reporting I have seen it in various projects where we used this report generation plugin.

**Comment by kmaterka** [comment]
It comes from damianszczepanik/cucumber-reporting. This plugin uses version 3.2.0, issue was fixed in newer versions.

As a workaround you can add:
buildscript {
    dependencies {
        classpath 'net.masterthought:cucumber-reporting:3.20.0'
    }
}

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
