### ISSUE TITLE
Configured cucumber suite does not show when executing 'gradle tasks'

### ISSUE THREAD

**Issue by trevorism** [commercehub-oss/gradle-cucumber-jvm-plugin#39]
I am on gradle 4.0.1
If I add `addCucumberSuite "acceptance"` to my build file, I can run `gradle acceptance`.

It only shows up in the task list if I run `gradle tasks --all`

You need to put the cucumberSuite task in a group: http://mrhaki.blogspot.com/2010/10/gradle-goodness-group-similar-tasks.html

**Comment by trevorism** [comment]
You can fix this by configuration
```
acceptance{
    group = "verification"
    description = "Runs cucumber tests"
 ...
}
```
but there should be a default.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
