### ISSUE TITLE
Not able to execute feature

### ISSUE THREAD

**Issue by paragkulkarnisqs** [commercehub-oss/gradle-cucumber-jvm-plugin#40]
Here is my build.gradle

buildscript {
  repositories {
   flatDir 
	{
		dirs "gradle/Jars/Cucumber masterthought" 	
	}  	 
  }
  dependencies {
    classpath "com.commercehub:gradle-cucumber-jvm-plugin:0.11" 
    classpath "net.masterthought:cucumber-reporting:jar:3.2.0"
    classpath "org.codehaus.gpars:gpars:jar:1.2.1"
    classpath "org.codehaus.jsr166-mirror:jsr166y:jar:1.7.0"
    classpath "com.fasterxml.jackson.core:jackson-databind:jar:2.9.0"
    classpath "com.fasterxml.jackson.core:jackson-core:jar:2.9.0"
    classpath "com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0"
    classpath "org.apache.logging.log4j:log4j-api:jar:2.7"
    classpath "org.apache.logging.log4j:log4j-core:jar:2.7"
    classpath "org.apache.velocity:velocity:jar:1.7"
    classpath "commons-io:commons-io:jar:2.5"
    classpath "org.apache.commons:commons-lang3:jar:3.4"
    classpath "commons-collections:commons-collections:jar:3.2.2"
    classpath "commons-lang:commons-lang:jar:2.6"
    classpath "joda-time:joda-time:jar:2.9.9"
  }
}

apply plugin: 'java'
apply plugin: 'com.commercehub.cucumber-jvm' 
  
addCucumberSuite 'cucumberTest'
  
cucumber {
    maxParallelForks = 3
}
    
cucumberTest {
    systemProperties['user.dir'] = projectDir
    stepDefinitionRoots = ['src/main/java/com/hooks', 'src/test/java/com/stepdefinition']
    stepDefinitionRoots = ['src/test/resources/features']
    tags = ['@15287']
    junitReport = true
    isStrict = true
}

repositories 
{
    //All sub-projects will now refer to the same 'libs' directory
	flatDir 
	{
		dirs "gradle/Jars" 
	}  	   
}
dependencies 
{
	compile fileTree(include: ['*.*'], dir: 'gradle/Jars')
	runtime fileTree(include: ['*.*'], dir: 'gradle/Jars')
	testCompile fileTree(include: ['*.*'], dir: 'gradle/Jars')
} 

Output
:processResources
:classes
:compileCucumberTestJava NO-SOURCE
:processCucumberTestResources NO-SOURCE
:cucumberTestClasses UP-TO-DATE
:cucumberTest

BUILD SUCCESSFUL

Total time: 0.51 secs

Gradle not executing my test case.
please help.
Please let me know the how project structure should be.

**Comment by JayStGelais** [comment]
This is a level of support that we do not offer on this project. Additionally it is difficult to determine why your tests aren't executing from just an excerpt from your build script. Directory structures play an important part in finding tests. 

Some things to remember when debugging your build:

- The cumber task is setup to find glue code and feature files in a gradle source set. The name of this source set is the argument you pass to addCucumberSuite()
- Glue code is scanned for in the source set in the packages (and their children) specified in _stepDefinitionRoots_
- Feature files are scanned for in the resources tree in the source set n the packages (and their children) specified in _featureRoots_
