### ISSUE TITLE
Features contained in recursive folders are not found

### ISSUE THREAD

**Issue by acorse** [commercehub-oss/gradle-cucumber-jvm-plugin#44]
*Context*
My .feature files are organized into multiple folders in order to ease .feature management
com.toto.features
	| folder1
	|	folder1.1
	|		|- f1.feature
	|		|- f2.feature
	|	folder1.2
	|		|- f3.feature
	|		folder1.2.1
	|			||- f4.feature
	|
	| folder2
	|		|- f5.feature
	|		|- f6.feature

featureRoots = ['com/toto/features']

*Seen*
It seems that not all the features files are scanned, some feature files are skipped and never played.
For example, f1.feature is OK, f2.feature is OK but f3 is NOT

I tried several configuration like
featureRoots = ['com/toto/features/folder1','com/toto/features/folder2']

for the same result.

    protected FileTree findFeatures(SourceSet sourceSet) {
        sourceSet.resources.matching {
            options.featureRoots.each {
                include("${it}/**/*.feature")
            }
        }
    }

**Comment by JayStGelais** [comment]
@acorse Can you provide a git repo that reproduces this behavior and link it.

**Comment by acorse** [comment]
I  tried to reproduce with a sample project and I couldn't. In my main project I have a lot of feature files (about 100 with an average of 5 scenario in each) in several folders / subfolders and I suspect that the folder scan is not over when tests are launched.

This implies that not all features are discovered and in the \test-results\cucumber\test folder I only have few files.

**Comment by acorse** [comment]
@JayStGelais I finally managed to reproduce it and you can checkout the project @ 
 https://github.com/acorse/featuresFoldersBug

Launch gradle task 'test' with VM option: -Dtags="'@todolist'"
It should run all features contained in the folder31todolist folder but only 'wunderlist' and 'google keep' are run.

FYI I use:
ext.cukesVersion = '2.0.1'
ext.seleniumVersion = '3.6.0'

**Comment by JayStGelais** [comment]
@acorse Can you pair your example down to make it portable on OSes other than windows and without dependencies on software being installed in specific locations. When I run this test suite on my Mac it just fails complete on not being able to find the firefox binary at C:/Program Files (x86)/Mozilla Firefox/firefox.exe

**Comment by JayStGelais** [comment]
Given the lack of a portable reproduction of this issue, I am going to close.
