### ISSUE TITLE
record and rerun failed cases

### ISSUE THREAD

**Issue by pacan1** [commercehub-oss/gradle-cucumber-jvm-plugin#46]
Hi - is it possible to use gradle config with your plugin to record and rerun failed test cases.
Thanks

**Comment by JayStGelais** [comment]
This is not a current feature of this plugin.

**Comment by pacan1** [comment]
Any plans to implement it?

**Comment by JayStGelais** [comment]
No. But we are open to pull requests if your interested in adding it.
