### ISSUE TITLE
Plug-in does not work with the Gradle Kotlin DSL

### ISSUE THREAD

**Issue by pinguinkiste** [commercehub-oss/gradle-cucumber-jvm-plugin#47]
When using the Gradle [Kotlin DSL](https://github.com/gradle/kotlin-dsl) the plug-in does not work anymore. The reason seems to be the use of Groovy's `metaClass` to add `addCucumberSuite`. This is not available from the Kotlin DSL.

Since more projects are moving to the Kotlin DSL I hope that this plug-in can either support it or document a way how it can be used with it.

**Comment by JayStGelais** [comment]
We would be open to accepting a merge request that resolves this conflict with the Kotlin DSL as long as it didn't break existing usages.
