### ISSUE TITLE
Support tag expressions

### ISSUE THREAD

**Issue by andrcuns** [commercehub-oss/gradle-cucumber-jvm-plugin#50]
Since cucumber version 2.0, the old style of providing tags has been deprecated in favour of of [tag-expressions](https://docs.cucumber.io/tag-expressions/)
`Support for '@tag1,@tag2' will be removed from the next release of Cucumber-JVM. Please use '@tag or @tag2' instead`
`Support for '~@tag' will be removed from the next release of Cucumber-JVM. Please use 'not @tag' instead`
To avoid having warnings or braking compatibility with latest releases consider implementing  support for tag expressions.

**Comment by andrcuns** [comment]
Actually, never mind. It will work out of the box when tag expression is provided as a single element to `tags` list. Only confusing thing is it still has to be a list. But I guess for backwards compatibility sake, it is not so bad.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
