### ISSUE TITLE
Octane integration

### ISSUE THREAD

**Issue by gajo4256** [commercehub-oss/gradle-cucumber-jvm-plugin#51]
Hi guys,

in our project we are using your plugin and ti is working wonderfully. 
We now have one request and we aren't quite sure how to do it or if it's even possible.
We need to run our tests with Octane, i.e. we need somehow to include OctaneCucumber class which will generate xml reports in the format for the Octane. It works if we include it as a part of the new project without the plugin, e.g.
@RunWith(OctaneCucumber.class)
public class TestRunner {}

Can it be done with the plugin somehow? 
Many thnx

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
