### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by aslakhellesoy** [commercehub-oss/gradle-cucumber-jvm-plugin#52]
I find it difficult to see what's changed in each version. Would you consider [keeping a CHANGELOG](http://keepachangelog.com/)?

**Comment by vigneshrr90** [comment]
We will add the changelog in our newer version @aslakhellesoy

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
