### ISSUE TITLE
Integration with Spring-Cucumber

### ISSUE THREAD

**Issue by mikesmithson** [commercehub-oss/gradle-cucumber-jvm-plugin#53]
We have started using Spring-Cucumber in our BDD tests and when we run the bddTest task, everything just hangs. The Spring application is a Boot Run application. We cannot get any further information than what I have provided since there are no errors or exceptions. The machines that are failing are Windows 10 machines. It does integrate with Mac and *nix machines.

**Comment by JayStGelais** [comment]
Unfortunately, without any further information such as specific error messages, there is not much we can do to help you with this issue.

Closing this issue. Feel free to submit a future issue if you are in a position to provide more details.
