### ISSUE TITLE
Retrofit the CucumberTask to implement JavaForkOptions or JavaExec

### ISSUE THREAD

**Issue by pgelinas** [commercehub-oss/gradle-cucumber-jvm-plugin#56]
The standard way with Gradle to launch a new JVM is through the JavaExec task and it also enables the Jacoco plugin to add coverage to test run with Cucumber. This would obsolete the JavaProcessLauncher in favor of a more standardized API.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
