### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by aniketksh** [commercehub-oss/gradle-cucumber-jvm-plugin#57]
Tried using gradle-cucumber-jvm plugin. Getting following error.

$ gradle cucumberTest
Download https://plugins.gradle.org/m2/com/commercehub/gradle-cucumber-jvm-plugi
n/0.8/gradle-cucumber-jvm-plugin-0.8.pom

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cucumberTest'.
> No signature of method: net.masterthought.cucumber.Configuration.setStatusFlags() is applicable for argument types: (java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean) values: [false, false, false, false]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
2 actionable tasks: 2 executed

**Comment by andrcuns** [comment]
Try latest 0.13 version. It works fine.

**Comment by JayStGelais** [comment]
Closing issue as this is addressed in a more current version.
