### ISSUE TITLE
Jenkins Failure for version 0.13 - Passed Reports Have No Features!

### ISSUE THREAD

**Issue by mikesmithson** [commercehub-oss/gradle-cucumber-jvm-plugin#58]
I am using version 0.13  and we are getting Jenkins build failures where we are getting the message "Passed Reports Have No Features!" on the console. We have no other information to share other than the json files for the test executions are being in the build/tests/cucumber directory and they look to be valid along with the other error log files, if any. However, our builds are marked as failing since the report generator appears to be failing. Any ideas? We really need this working with reports for our development efforts.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
