### ISSUE TITLE
Running scenarios in parallel 

### ISSUE THREAD

**Issue by getmetorajesh** [commercehub-oss/gradle-cucumber-jvm-plugin#59]
I see currently the plugin supports running features in parallel but is there a way to run scenarios in parallel.

**Comment by andrcuns** [comment]
There is not. The plugin creates parallel forks by feature files only. To run parallel scenarios, some parser would have to be created that reads scenarios from feature files.

**Comment by shweta2202** [comment]
@getmetorajesh  I maintain this plugin, as I know there is a community out there that finds it useful, but this maintenance has mostly been limited to managing community submitted pull requests. If you can figure out a way to make your use case work and submit a pull request that doesn't break any existing tests I would be thrilled to include it in the plugin and publish a new version.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
