### ISSUE TITLE
Running java 9 test is failing due to not loading xml.bind module

### ISSUE THREAD

**Issue by sreejithp** [commercehub-oss/gradle-cucumber-jvm-plugin#60]
Thanks for the plugin!. I love it. 

I was running the tests in Java 9 tests and failed because of xml.bind module not being loaded. I know we need to load the modules but was wondering how can I add this java parameter. I can see jvmArgs being added to .14 build. Looks like it is not there in gradle repo yet. Let me know where else i can get this build or can you please update gradle repo to the latest build. OR just let me know if there is any other way i can add jvm args to load modules in .13 build

**Comment by shweta2202** [comment]
Thanks @sreejithp . I will release the new version this week.

**Comment by sreejithp** [comment]
Hey @shweta2202, Thanks for the update but when you think we can expect this to come?

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
