### ISSUE TITLE
Getting error when configured custom cucumber plugin

### ISSUE THREAD

**Issue by SM-Rahman** [commercehub-oss/gradle-cucumber-jvm-plugin#65]
In cucumber junit we configure the custom plugin in RunCukesTest.java in @CucumberOptions
plugin = {"x.y.z.CustomPlugin:custom/folder"},
But when tried to configure in gradle in getting the bellow gradle compilation error
cucumberTest{
--------------///some steps
featureRoots = ['features']
 plugins = ['x.y.z.CustomPlugin:custom/folder']    
    junitReport = true
    isStrict = true
//-------- some steps
}

* What went wrong:
A problem occurred evaluating root project 'TestProject'.
> Cannot set the value of read-only property 'plugins' for root project 'TestProject' of type org.gradle.api.Project.

How to provide custom cucumber plugin to the gradle-cucumber-jvm-plugin?
I looked at documentation and searched online but could not find it. Please help me resolve this issue.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
