### ISSUE TITLE
Please create a new release

### ISSUE THREAD

**Issue by spiffomatic64** [commercehub-oss/gradle-cucumber-jvm-plugin#66]
Would love the ability to take advantage of the jvmargs option added in aed0b6df8e0cfb1649b9c03577f8e4ba7f830706

**Comment by vpappula** [comment]
+1
I am facing memory issues (heap and OOM) towards the end of execution. I would like to try the jvmArgs option to see if I can overcome the memory issues.

**Comment by spiffomatic64** [comment]
It looks like a release WAS made in April, but its not here, just available on the gradle repo (as far as I could see) https://plugins.gradle.org/plugin/com.commercehub.cucumber-jvm

This is working for my needs at least.

**Comment by vigneshrr90** [comment]
@spiffomatic64 @vpappula I will get the release out within 2 days , sorry for delay in response.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
