### ISSUE TITLE
Support for custom cucumber runners

### ISSUE THREAD

**Issue by muhatashim** [commercehub-oss/gradle-cucumber-jvm-plugin#67]
Instead of statically running `cucumber.api.cli.Main` all the time, the ability to redefine that to use a custom main class would be greatly beneficial for those that want to use a custom resource loader/class loader or Runtime. Currently there is no way of using custom loaders unless we can change the main class.

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
