### ISSUE TITLE
Output is very difficult to find

### ISSUE THREAD

**Issue by mattcorey** [commercehub-oss/gradle-cucumber-jvm-plugin#7]
Console output is very difficult to find.  It should be available in the console window, if at all possible.

**Comment by zarry** [comment]
Hey This Guy! @mattcorey

Not sure we have the bandwidth to tackle this at the moment but we are accepting pull requests!  @JayStGelais might have more thoughts.

**Comment by JayStGelais** [comment]
@mattcorey Are you referring to the stdout/stderr ourput of the cucumber cli? Because we run tests in parallel it would be very tough to read if many tests were weaving their output together at the same time.

If you wanted to add logic that set the output to the console if the runner was not running multiple forks, I would accept that pull request.

**Comment by mattcorey** [comment]
I am referring to that output - I agree that the console is not the right place for multithreaded.  How difficult would it be to add a link to the report page, along with every Scenario?  That way you're at least looking in one place.

**Comment by JayStGelais** [comment]
It's possible. We are already adding the screen shots, so there is examples of how to add files to the report. 

I'd accept that pull request as well.

**Comment by mattcorey** [comment]
I took a look at this the other day, and using the 'embeddings' capability that the screenshots use won't work, at least not without some adjusting.  'embeddings' fields can be added at the 'step' or at the 'scenario' level, but the existing output files are created at the Feature level.

Adding these at the Scenario level would be the cleanest solution, I believe -- I'll poke around to see if the output files can be created per scenario.  Any other thoughts would be appreciated.

**Comment by JayStGelais** [comment]
I don't see a good answer for this. The embedding will embed the entire .out and .err files for the feature, creating copies for each scenario that grow as the feature finishes. 

Would something as simple as task output that told the user where the cucumber cli output was written to suffice?

**Comment by mattcorey** [comment]
It would be a decent first step, but a link is what I'm really looking for.  If we have to deal with the output at the feature level, I'd be happier updating the template to provide a link to the stdout and stderr files, which would be a change to the reporting project, not the grade build.  I plan to investigate this weekend.

M

**Comment by mat013** [comment]
I had the same issue...

Especially when we are going to run at a CI server and it fails and we are not able to get the files easily, However I would like to see the entire log when it fails, so what I did was the following in the CucumberRunner.run: in the section after the checking the resultFile:

                if (resultsFile.exists()) {
                    List<CucumberFeatureResult> results = parseFeatureResult(resultsFile).collect {
                        log.debug("Logging result for $it.name")
                        createResult(it)
                    }
                    results.each { CucumberFeatureResult result ->
                        testResultCounter.afterFeature(result)

                        if(result.failedSteps > 0) {
                            log.error("{}:\r\n {}", sourceSet.name, consoleOutLogFile.text)
                        }
                    }

**Comment by JayStGelais** [comment]
@mat013 This looks like a reasonable change. If you want to submit a pull request, we would accept this.
