### ISSUE TITLE
Output log files are being locked

### ISSUE THREAD

**Issue by mattcorey** [commercehub-oss/gradle-cucumber-jvm-plugin#8]
I'm seeing occasional file locking occuring with the files in test-results/cucumber/cucumberTest/features.<feature-name>.feature-err.log, and feature-out.log.  

It doesn't seem to impact the running of the cucumberTest task, but it does cause problems when running tasks like 'gradle clean'.  Re-running the cucumberTest task tends to release the locks.

I've not yet determined a pattern, whether this is 100% of the time or not

**Comment by JayStGelais** [comment]
Is this on Windows?

**Comment by mattcorey** [comment]
Sadly, yes

**Comment by davidmc24** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to fork the project and work on it further yourself under the terms of the project license if desired.
