### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by jontxo** [commercehub-oss/gradle-cucumber-jvm-plugin#9]
Hello

I have created a gradle project 
[selenium_java_cucumber.zip](https://github.com/commercehub-oss/gradle-cucumber-jvm-plugin/files/269238/selenium_java_cucumber.zip)

but I am unable to get it to work with the plugin. In all the executions the task of the plugin is executed correctly but no features are found and there are no messages in the console.

Could you please provide me a project with the plugin in order to try to find out where is the problem in mine.

Regard
Regards

**Comment by JayStGelais** [comment]
I'm reluctant to open a zip file from a stranger on the internet. Could you provide a suitable example project on a public github repo?

**Comment by jontxo** [comment]
Sure

https://github.com/jontxo/cucumber-selenium-and-gradle.git

I have just uploaded it to github. Please let me know if you have any problem accesing. 

Regards

**Comment by JayStGelais** [comment]
@jontxo Just sent you a pull request with a working example.

**Comment by JayStGelais** [comment]
Saw that the pull request was accepted. Closing this issue.

**Comment by jontxo** [comment]
Hello

Thank you for your help. I think that the problem was in the way I was creating the packages and the folders where the features file and the steps file are saved. 

Regards
